### ISSUE TITLE
Current version of this and Brackets 1.3 don't play well together. 

### ISSUE THREAD

**Issue by equinox** [JonathanWolfe/file-tree-exclude#12]
I'm back... :(

So, the issue I've been facing is basically described [here](https://groups.google.com/forum/#!topic/brackets-dev/63XpRpL7bMg) -- removing this extension fixes that. I think for some reason maybe it's matching all files and for some dumb reason excluding all files and folders. I've tried multiple different projects with different file types and all get excluded _only when the file tree is interacted with_. That means when I right click a file/folder, left clicking etc also, I was only able to find this out because when opening the editor, if I've got an open file in the 'working files' section (I use the tab extension, but it's basically the same) the files are gone from the start and I don't even get to interact with them.

If this wasn't clear (I don't blame you for not understanding), just say and I'll try write it more clearly.

**Comment by JonathanWolfe** [comment]
I'm going to wait on any Brackets 1.3 issues until it goes stable. You're probably right, something might have changed in 1.3 with file paths and now matches are always returning true. Post your settings so I can test with them later.

Sorry you've been having issues with the plugin.

**Comment by equinox** [comment]
Yeah, sorry, this was more of a warning rather than "fix this now!!!" kinda post. I removed all of the extension's settings (so there was nothing in the preferences) to make sure that that wasn't the issue early on, and still had the issue afterwards.

**Comment by JonathanWolfe** [comment]
Test with the new 0.5.3 and let me know if you're still having issues. Works fine for me on the brackets preview version.

**Comment by equinox** [comment]
Just tested on the latest release branch, works as expected once more!

Closing.
