### ISSUE TITLE
Problems when the project path has a "git" folder

### ISSUE THREAD

**Issue by uxDaniel** [JonathanWolfe/file-tree-exclude#13]
First of all, thanks a lot for this great extension!

Then, I have had issues with a project located at, say `/Users/zlapper/git/myproject/`, that made all my files disappear in the file tree.

I was able to show them back removing the `".git"` entry from the preferences file, but that of course removes the (desired) behavior of ignoring the .git folder. I tried escaping the `"."` from that string with no luck, so I my guess is that there is some kind of parsing problem with those preferences paths.

Hope it helps. Thanks a lot in advance!

**Comment by JonathanWolfe** [comment]
Yeah I suspected this might happen after someone made a similar claim. I'm still seeing what I can do to try and get this matching down just right.

**Comment by JonathanWolfe** [comment]
I just uploaded a new version 0.5.3 that should fix your issue. Let me know!

**Comment by uxDaniel** [comment]
Awesome! Yes, it seems like that fixed it. Thanks a lot!
