### ISSUE TITLE
Doesn't work on OSX

### ISSUE THREAD

**Issue by AriMcBrown** [JonathanWolfe/file-tree-exclude#15]
The plugin doesn't seem to obey the configuration on a Mac (OSX 10.10.3)

I want to exclude the ".sync"-folder (BTSync) and the "Icon"-file MacOS places in every folder.

So I added the following two lines in the brackets.json:

```
{
...
"jwolfe.file-tree-exclude.list": [
      ...
      "/.sync/",
      "Icon"
    ]
}
```

**Comment by AriMcBrown** [comment]
hmm, it does seem to work on the "vendor", just tested it. So it is doing something, just not everything.

**Comment by JonathanWolfe** [comment]
Remove your / around `.sync`. And `Icon` isn't a file, you're forgetting the file extension (something like `.icns` if I remember right).
