### ISSUE TITLE
Excludes some, not others?

### ISSUE THREAD

**Issue by bobrocke** [JonathanWolfe/file-tree-exclude#17]
I have:

```
"jwolfe.file-tree-exclude.list": [
    "node_modules",
    "bower_components",
    ".git",
    "dist",
    ".codekit-cache",
    "backup",
    "config.codekit",
    "Vagrantfile",
    ".vagrant",
    "bin",
    "cache",
    "logs",
    "images",
    "assets"
]
```

which excludes many of these nicely. But it doesn't exclude `.codekit-cache` nor `backup`. Why should that be?

![brackets json www br dev brackets](https://cloud.githubusercontent.com/assets/2962426/8026434/4a83f424-0d43-11e5-81c7-99b5b12a5a4a.jpg)

**Comment by bobrocke** [comment]
Both `.codekit-cache` and `backup` are empty folders. Could that be part of the problem?

**Comment by JonathanWolfe** [comment]
Hmmm, I don't know really. I recommend you open the plugin file (in brackets) `Help -> Show Extensions Folder -> user -> jonwolfe.file-tree-exclude` and edit the `main.js` file to uncomment the console logs at the bottom, then look at the brackets debug tools (in brackets) `Debug -> Show Debug Tools`.

**Comment by bobrocke** [comment]
Any clues in that:

```

main.js:74 regex /node_modules|bower_components|.git|dist|.codekit-cache|backup|config.codekit|Vagrantfile|.vagrant|bin|cache|logs|images|assets/
main.js:75 list Array[14]0: "node_modules"1: "bower_components"2: ".git"3: "dist"4: ".codekit-cache"5: "backup"6: "config.codekit"7: "Vagrantfile"8: ".vagrant"9: "bin"10: "cache"11: "logs"12: "images"13: "assets"length: 14__proto__: Array[0]
main.js:76 projectPath /Users/bob/Dropbox/SyncedSites/vhosts/www.br.dev/
main.js:77 /Users/bob/Dropbox/Application Support/Brackets/extensions/user/jonwolfe.file-tree-exclude/ true
main.js:78 README.md true
main.js:79 verdict true show
```

**Comment by JonathanWolfe** [comment]
That's just for `README.md` you'll need to find the ones related to `.sass-cache` and `backup` in those logs.

**Comment by bobrocke** [comment]
OK...... After several reloads, those folders are now being excluded. So, I don't know what happened, or why a single reload didn't get things working, but they are now!
