### ISSUE TITLE
Extension broke after latest update

### ISSUE THREAD

**Issue by Nickersoft** [JonathanWolfe/file-tree-exclude#19]
I just update FTE to the latest version, and upon Brackets reload, my directories (node_modules, dist) were no longer ignored by the file tree and I received the large project warning from Brackets. I've since reloaded Brackets as well as restarted it, but the problem has persisted. Is this a known issue? Is there a recommended way to resolved it?

**Comment by JonathanWolfe** [comment]
Reverted back to `0.6.0` codebase until I figure out why `0.6.1` breaks for some people.
