### ISSUE TITLE
Per project setting not working

### ISSUE THREAD

**Issue by matthiasg** [JonathanWolfe/file-tree-exclude#2]
Not sure how this is supposed to work, but I just opened my main project with Brackets for the first time and immediately required file-tree-exlude since i ran into the limit issue. Thus there is no searching at all.

Now i have Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 
and installed file-tree-exlude from via the extension manager.

I first tried globally editing the exlude list as per documentation. I restarted then, that seemed to work and the matching folders/files are no longer in the tree on the left.

Now I created a local .brackets.json file in the root of the added directory. But those contents seem to be ignored. 

Also I would like to know how directory slashes are handled. I would like to specify via forward-slash, but i also develop on Windows not just Mac and thus i wouldnt want to add every entry twice. How is this handled internally ?

Thanks for the work btw..

**Comment by JonathanWolfe** [comment]
Sorry I didn't see this sooner, Github didn't give me a notification!

The local override is handled via Brackets because it should import the global preference file then the .brackets.json (overriding conflicting/duplicated settings).

I was just following the developer docs (though out of date) and didn't check so I'll do that and get a fix in.

Oh, and directory slashes are handled with backslashes. (ex: `this/directory/is/hidden`)

**Comment by PhiLhoSoft** [comment]
Indeed, I use Brackets on Windows too, and the project settings are just ignored (while the readme tells it should override the default / global one).
Ideally, I would prefer to have a merge of the two: define global settings for .git, node_modules and other frequently found folder / files, and adding project-specific settings.

**Comment by simonfanz** [comment]
I also seem to have this issue on windows - the project settings just seem to be ignored.

**Comment by sandcastle** [comment]
I'm using a Mac and also having the same issue - so looks like this is affecting all platforms... I have other local settings working fine - it it must be related to the array.

I have lodged a bug on the brackets repo for this:

https://github.com/adobe/brackets/issues/10827

**Comment by sandcastle** [comment]
FYI - Comments from the Brackets dev team:

> @sandcastle The type of data doesn't matter to the preferences system. It's all a matter of what the extension is expecting, so this is a bug with the extension.
> 
> I'm not sure why the author calls [Glenn Ruehle's exclude-folder](https://github.com/gruehle/exclude-folders) plugin "defunkt" -- as far as I know it still works, so maybe try that plugin instead.

https://github.com/adobe/brackets/issues/10827#issuecomment-89585648

**Comment by JonathanWolfe** [comment]
I am planning to get around to figuring this out and fixing it soon!

**Comment by MattDiMu** [comment]
Thx, would appreciate as solution as well (as projects are shared via git and I'd like to share settings like that).
