### ISSUE TITLE
Breaks latest version of Brackets SASS

### ISSUE THREAD

**Issue by jan-herman** [JonathanWolfe/file-tree-exclude#20]
Latest version of Brackets SASS (2.0.3-132) isn't somehow compatible with this extension. After update SASS no longer compiles when an imported file is saved/changed.

**Comment by JonathanWolfe** [comment]
Have you tried removing `.sass-cache` or other relevant exclusions to see if it's related to specific files/folders?

**Comment by jan-herman** [comment]
Not really. I was using your extension just to hide empty folders in my project which are required later on in the development process and have nothing to do with SASS.

**Comment by JonathanWolfe** [comment]
Post your exclude settings if you could because the only way these plugins can interact is via the exclusions.

**Comment by jan-herman** [comment]
Just found the problem. I feel stupid. At some point I tried excluding style.css.map via the brackets.json file at the project folder and then I copied this file across bunch of other projects. Nevertheless this didn't affect the older version of brackets-sass, but now it couses problems.
