### ISSUE TITLE
Can't exclude certain files

### ISSUE THREAD

**Issue by RuinTD** [JonathanWolfe/file-tree-exclude#21]
You can't exclude specify a specific path (like "folder/file.txt") to exclude, but [it's easy to see why](https://github.com/JonathanWolfe/file-tree-exclude/blob/master/main.js#L65-L73). Why are the path and file name tracked separately? Shouldn't you feed the entire path to minimatch?

**Comment by JonathanWolfe** [comment]
[v0.6.1](https://github.com/JonathanWolfe/file-tree-exclude/releases/tag/0.6.1-beta) did that but contained issues for some people and I haven't gotten around to checking out why.

**Comment by RuinTD** [comment]
Maybe [isaacs/node-glob](https://github.com/isaacs/node-glob) would help.

**Comment by JonathanWolfe** [comment]
It's not quite as simple as that since brackets handles their filesystem super oddly. I am trying my best though to make an easy interface for this though.

**Comment by JonathanWolfe** [comment]
For now, you can watch issue #16 as that one should resolve your issue as well.
