### ISSUE TITLE
Latest versions is broken (Win 7)

### ISSUE THREAD

**Issue by stowball** [JonathanWolfe/file-tree-exclude#23]
I've just upgrade to 0.8.0 from 0.6.2 and it's broken. node_modules doesn't hide, even though it's in brackets.json by default and an empty C: folder appears in the file tree :(

**Comment by JonathanWolfe** [comment]
I'm not seeing this in my clean Win7 VM. edit the file to turn on the logs and paste those here.

**Comment by m66n** [comment]
I'm on Linux and seeing the same thing. Which file do I edit to turn on the logs?

**Comment by Cycymomo** [comment]
Same here. The 0.8.0 seems broken.

You can downgrad it by installing the last one : https://github.com/JonathanWolfe/file-tree-exclude/releases (copy/paste into the plugins foler)

**Comment by AdriVanHoudt** [comment]
Seems to be a problem with folders with a lot in it. 
I get the 30000 files error and console prints 

```
 temp [] flatten.js:30
flattened [] main.js:101 
 _unmatched_files [] main.js:102
```

Maybe somehow the error gets thrown before the exclude? Since the error states that `features may behave as if the project is empty` which from the logs seems like the case.

Also can you disable the console logging? Printing a few arrays with a few thousand elements is not so fun for perf and does not add value besides debugging (which you don't need in general)

EDIT: on mac 10.10.5 and reverting works :+1:

**Comment by SeanHub** [comment]
Same here. No folder excludes on Windows 7.

**Comment by JonathanWolfe** [comment]
Just pushed an update to `0.8.1`, does that help?

**Comment by djusv** [comment]
0.8.1 doesn't work for me

**Comment by depiction** [comment]
Same issue, but I'm on a Mac.

**Comment by samura** [comment]
Also not working after latest update on a mac with version 0.8.1

**Comment by JonathanWolfe** [comment]
I think it's a plugin conflict. Can you guys try using FTE just by itself and see if it works then?

**Comment by samura** [comment]
tried disabling everything. same problem.

**Comment by djusv** [comment]
I tried debugging it, I put a breakpoint on `line 72` in the `main.js` and tried `console.log(files)`
but somehow I only get an empty array from `ProjectManager.getAllFiles().then....`

Maybe i found out why I get an empty Array, looking at brackets sourcecode = [link](https://github.com/adobe/brackets/blob/master/src/project/ProjectManager.js#L1372).
When you have too many files the list returned is empty thus no filtering is done.

**Comment by JonathanWolfe** [comment]
Just to verify, everybody having the issue is on Brackets 1.4, yes?

**Comment by JonathanWolfe** [comment]
Good catch @djusv, I'll check that out when I get a free moment.

**Comment by djusv** [comment]
@JonathanWolfe  yes, I'm using Brackets 1.4.

**Comment by samura** [comment]
yes, 1.4.

**Comment by simoneduca** [comment]
@JonathanWolfe Yes, Brackets 1.4 on Yosemite 10.10.4

**Comment by AdriVanHoudt** [comment]
1.4 here as well, not testes disabling other plugins though yet

**Comment by kmoskwiak** [comment]
same here - brackets 1.4, ubuntu 14.04

**Comment by JonathanWolfe** [comment]
Just pushed up `0.8.2` everyone, should (hopefully) solve the problem.

**Comment by AdriVanHoudt** [comment]
nope :/ although the error doesn't show anymore (because of the lag?) Brackets hangs like crazy (on project load) for a while and then it is fine but the folders don't seem excluded (can still see them in the file tree on the left)

**Comment by m66n** [comment]
I confirm that. Brackets is pegging a CPU, and the 30,000 limit dialog appears. I've disabled all extensions on Brackets 1.4.

**Comment by JonathanWolfe** [comment]
The CPU hang is from Brackets gathering info every file in your project, I'll write a small optimization to help that, but you'll always have that when opening tremendously large folders.

**Comment by AdriVanHoudt** [comment]
I don't have it with version 6.x though

**Comment by m66n** [comment]
Same here. I got maybe 3% CPU utilization on the same project using 0.6.2.

**Comment by JonathanWolfe** [comment]
Because the pre-`0.8.x` branches filtered files in-place, which is good for performance, but isn't accurate because of oddities in the way Brackets wrote their filesystem. The `0.8.x` branch gathers all files then filters for total accuracy at the cost of on-load perf in large projects.

**Comment by AdriVanHoudt** [comment]
Well don't take this the wrong way but I will stick with 0.6 then. I switch a lot between projects and for me it is mainly about build, node_modules and bower_components and it works. The accuracy in my case does not weigh up against waiting for 20 seconds for my project to be ready. But still awesome plugin!

**Comment by JonathanWolfe** [comment]
Maybe I'll revert back to the `0.6.x` branch again for the Brackets Registry and see if I can find a best-of-both-branches method later.

**Comment by AdriVanHoudt** [comment]
Yeah I don't know the cases this would solve but my best guess is that most
users would not go for the tradeoff at hand :/ thanks for the super quick
help though! Really appreciate it

**Comment by simoneduca** [comment]
@JonathanWolfe : thanks for being so responsive! I second @AdriVanHoudt, bring back `0.6.x` :)

**Comment by JonathanWolfe** [comment]
@AdriVanHoudt it solves the issue of #16.
@simoneduca I did. http://brackets.dnbard.com/extension/jonwolfe.file-tree-exclude

**Comment by simoneduca** [comment]
@JonathanWolfe great: no lagging, no error, no conflict with GitBrackets either. Thanks.
