### ISSUE TITLE
Latest update is erroring

### ISSUE THREAD

**Issue by simoneduca** [JonathanWolfe/file-tree-exclude#24]
I have installed the latest suggested update from Brackets extension manager and now I'm getting this

![screen shot 2015-09-03 at 17 03 36](https://cloud.githubusercontent.com/assets/8989606/9663709/c6a0cbf4-525d-11e5-89f7-5c4e2a103631.png)

I've tried to remove the extension and reinstall it, but it didn't help.

Is there a stable version available or can @JonathanWolfe  revert breaking changes?
Thanks

**Comment by JonathanWolfe** [comment]
https://github.com/JonathanWolfe/file-tree-exclude/releases/tag/0.6.2

Keep track of issue #23 for updates.
