### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CydGoblin** [JonathanWolfe/file-tree-exclude#26]
Tested on mac maverick and windows 10, it stopped working one day :disappointed:

**Comment by JonathanWolfe** [comment]
I haven't pushed an update in almost 3 months. And Brackets hasn't updated either.

You'll need to provide more info.

**Comment by CydGoblin** [comment]
How can i provide more information?
On mac i installed brackets and the plugin and it was not working on windows it just stopped working one day.

**Comment by JonathanWolfe** [comment]
What does the debugger say?

**Comment by CydGoblin** [comment]
![image](https://cloud.githubusercontent.com/assets/4932347/10211668/b8529b76-67b2-11e5-8f58-d4c495db218e.png)
is this what you need?

**Comment by JonathanWolfe** [comment]
You can try removing and re-adding FTE.

**Comment by CydGoblin** [comment]
It's the only plugin installed. I'll try a clean install again and see what happens.
update: Clean install, problem remains
update 2: it's working again. I did nothing, it just started to work again one good day...
