### ISSUE TITLE
I can't specify any deep exclusions?

### ISSUE THREAD

**Issue by AlbinoGeek** [JonathanWolfe/file-tree-exclude#29]
For example:

```
    ".meteor/local"
```

_cough_ , this is the build folder; often containing 10,000+ files.

---

I know I could hide the entire ".meteor" folder, but sometimes you need access to this.  Likewise, hiding of the entire ".git" is not recommended; but you can hide the objects, and other folders; still keeping access to refs, branches, etc.

**Comment by AlbinoGeek** [comment]
Nevermind, after some testing (and it was EXFAT's fault), I was able to get it to work.

**Comment by DaddyWarbucks** [comment]
What was the resolution to this?
I want exclude all all .css files in my `src` dir, but not in my `build` dir.
