### ISSUE TITLE
About a setting method of an extension

### ISSUE THREAD

**Issue by ina6ra** [JonathanWolfe/file-tree-exclude#3]
I'd like to establish an extension.
Brackets froze by the following setting.

> .brackets.json

``` json
{
    "jwolfe.file-tree-exclude.list": [
        "node_modules",
        "bower_components",
        "dist",
        "*.sql"
    ]
}
```

**Comment by JonathanWolfe** [comment]
Sorry I didn't see this sooner! Github didn't send me a notification.

A quick note:  `*.sql` should actually just be `.sql`. The current extension assumes everything is *.
