### ISSUE TITLE
Not able to undo (ctrl-z) after saving

### ISSUE THREAD

**Issue by basickarl** [JonathanWolfe/file-tree-exclude#31]
For some reason this plugin seems to (I assume) erase my history so I'm not able to undo after saving.

Running version of brackets on ubuntu 14.04:
Release 1.6 experimental build 1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 14:45:31 GMT+0000

**Comment by ThijsBroersen** [comment]
Confirmed here! 
Running Ubuntu 15.10 and Intel XDK with build-in Brackets

**Comment by basickarl** [comment]
Hmm after having uninstalled this plugin, the issue still arises. Heres the issue: https://github.com/adobe/brackets/issues/11826

**Comment by ThijsBroersen** [comment]
Disabling the plugin works for me, so far the issue is not arising anymore.
