### ISSUE TITLE
No folders nor files showing up

### ISSUE THREAD

**Issue by johnpapa** [JonathanWolfe/file-tree-exclude#4]
I installed this and no folders nor files appear. Even when I removed all exclusions.

**Comment by johnpapa** [comment]
If I do this it works:

```
    "jwolfe.file-tree-exclude.list": [
        "node_modules"
    ]
```

But if i leave in the .git files or some of the other default,s NO FILES show up

**Comment by JonathanWolfe** [comment]
I'll look into it. What platform and brackets version are you on?

**Comment by didlich** [comment]
I installed the plug-in today, after a refresh of the file tree all the files disappear.
I use the DEB installer for my ubuntu 14.04, with Brackets
version: Release 1.2 experimental build 1.2.0-15697 (release 8f82e2a97)

**Comment by EvHaus** [comment]
I'm having the same issue but only for certain projects.

**Comment by JonathanWolfe** [comment]
@globexdesigns Can you be more specific or provide examples?

**Comment by EvHaus** [comment]
My Brackets settings file has the following defined:

```
    "jwolfe.file-tree-exclude.list": [
        "node_modules",
        "bower_components",
        ".git"
    ]
```

In most of my Brackets projects, this does the right thing. It hides just those three folders if they exist in the project directory. However, when I load one of my Brackets projects (/local/myname/Git/myproject/dashboard/) into Brackets, I see 3 random empty directories in the Brackets file tree from my projects but most of the rest of the files are invisible.

![screen shot 2015-04-17 at 3 13 36 pm](https://cloud.githubusercontent.com/assets/226640/7211848/3a7bd4ea-e514-11e4-9849-799e88482b7f.png)

From what I can tell there is nothing particularly different about this project. So I'm not sure why the others work, but this one is throwing file-tree-exclude for a loop.

Furthermore, changing the list of directories under the "jwolfe.file-tree-exclude.list" setting, has absolutely no effect on this behaviour.

**Comment by JonathanWolfe** [comment]
Remove `.git` from your settings and see if all your files come back. It may be a matching issue because of the path.

**Comment by EvHaus** [comment]
It didn't help. Even if I completely clear the exclude list (ie. leave as []) I still have this issue.

_Edit_ Nevermind. I tried it again and removing `.git` helped resolve the issue. I must have forgotten to refresh last time.

**Comment by JonathanWolfe** [comment]
The new version 0.5.3 might help with this. Test and let me know.
