### ISSUE TITLE
Excluding files in the root of a project

### ISSUE THREAD

**Issue by simonfanz** [JonathanWolfe/file-tree-exclude#5]
I'm probably just using incorrect syntax, or perhaps this is not possible, but I would like to exclude html files in the root of my project, while displaying them in subfolders. 

I've tried "*.html", /*.html", "/.html" and a couple of other variations, but none seem to work (The first one hides all content of a folder called "html" in my project, but not the html files in the root of my project)

Is it possible to exclude files in the root by wildcard or similar?

**Comment by JonathanWolfe** [comment]
Not currently (unless you're damn good at regexs), sorry. That is a planned feature in the future though.

**Comment by simonfanz** [comment]
OK, thanks for the reply. Easy enough to move these files into a folder and then exclude that way :)
