### ISSUE TITLE
Extension not excluding some dirs

### ISSUE THREAD

**Issue by rtubio** [JonathanWolfe/file-tree-exclude#6]
My configuration for the extension is as follows (.brackets.json at the root of the project):

```
{
    "useTabChar": false,
    "tabSize": 4,
    "spaceUnits": 4,
    "closeBrackets": false,
    "showLineNumbers": true,
    "styleActiveLine": false,
    "wordWrap": false,
    "linting.enabled": true,
    "linting.collapsed": false,
    "quickview.enabled": true,
    "jwolfe.file-tree-exclude.list": [
        "node_modules",
        "lib",
        ".git",
        "dist",
        ".coverage",
        ".sass-cache"
    ]
}
```

As you can see in the attached screenshot, the directories "node_modules" and "dist" have been exluded, but ".coverage", "lib" and ".sass-cache" are still there. Is there anything that I am doing wrong?

I already try reloading brackets after changing the configuration file.

![screenshot from 2015-04-04 11 31 53](https://cloud.githubusercontent.com/assets/5666358/6994001/648fa0ba-dabd-11e4-90d1-d6bb68d253fd.png)

**Comment by JonathanWolfe** [comment]
Per project settings (`.brackets.json`) is currently broken. See issue #2 .
