### ISSUE TITLE
Filesystem Access Issue

### ISSUE THREAD

**Issue by rawveg** [JonathanWolfe/file-tree-exclude#7]
Building my exclude list, I managed to leave Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) running on Windows XP (sigh), without any filesystem access. The folder list disappears, as does the button that allows you to browse a new folder. You can't open the preferences file either, and other filesystem functions appear compromised.

I narrowed this down to a single offending entry

"*.bat"

**Comment by JonathanWolfe** [comment]
so adding `.bat` to your config freezes brackets?

**Comment by rawveg** [comment]
*.bat 

Brackets doesn't freeze, but all files stem functions appear to fail. So can't open the preferences file from the menu, the filesystem list in the left panel is unpopulated and the button enabling you to browse the filesystem disappears. I have been consistently able to reproduce this, removing the entry and putting it back.

**Comment by JonathanWolfe** [comment]
I already fixed this issue, but because the brackets extension registry was down, I wasn't able to upload the new version.

I finally did so you should see the update in Brackets and be good to go.
