### ISSUE TITLE
Empty folders showing since latest update

### ISSUE THREAD

**Issue by equinox** [JonathanWolfe/file-tree-exclude#8]
I tried to find some sort of changelog, but couldn't. Therefore, I am unsure whether this is intended behaviour or not...

![](http://i.imgur.com/JumZFm2.png)

As you can see above, a few of the folders included in the preferences are there, but they're empty. Also, in the previous version the configuration I had worked just how I wanted: it has the node_modules folder and inside the modules were also present, however, none of their contents were. Just the named folders that were empty, this is no longer the case (all the contents are shown again).

**Comment by equinox** [comment]
I went back a version, works as expected. Again, though, without any sort of changelog obvious I'm not sure what has changed and whether it is worth upgrading or not. 
(I added e2e in the exclusions below after changing the extension -- that was the only change)
![](http://i.imgur.com/vCs9Rl6.png)

**Comment by JonathanWolfe** [comment]
I'll include a fix for this regression in the next version.

**Comment by equinox** [comment]
Upon trying the new version there's only one file that I just can't seem to exclude! The ".sass-cache" is the only one I can't seem to get rid of (possibly due to - instead of _? -- all attempts were just shots in the dark, so sorry if it's my fault, all other folders are exactly how I want them without having to change them, so that works great!).
![](http://i.imgur.com/YcsUeQ3.png)

**Comment by JonathanWolfe** [comment]
Crap. I'm removing the dash in my special characters regex. I'll push up a
minor update tomorrow!

**Comment by equinox** [comment]
I could submit a PR, if you'd like (I removed it myself and confirmed it now removes that ".sass-cache" folder).

**Comment by JonathanWolfe** [comment]
Sure!

**Comment by JonathanWolfe** [comment]
Merged and pushed up to the registry!
