### ISSUE TITLE
doesn't work at all.

### ISSUE THREAD

**Issue by maxwowpow** [JonathanWolfe/file-tree-exclude#9]
Test project:
https://mega.co.nz/#!QQlS3bwB!05DTwtmbdAtOYJ0A_pnNmtnFq2N0ppeXWnsYIysBOY8

.brackets.json

```
{
    "jwolfe.file-tree-exclude.list": [
        "/bin/"
    ]
}
```

**Comment by RevanProdigalKnight** [comment]
Looking at the code, that would probably be because right now it doesn't actually look for a project-local `.brackets.json`. My guess is that the readme was updated for a feature that hasn't been added yet.

**Comment by maxwowpow** [comment]
ok, global brackets.json works, so this is a brackets' issue?

**Comment by RevanProdigalKnight** [comment]
No, like I said, the code isn't even looking for a project-local `.brackets.json` at the moment, so it's a plugin issue.

**Comment by JonathanWolfe** [comment]
The Brackets docs so preferences (global and project) should be handled automatically before I ever get to it, but that doesn't appear to be the case and I haven't gotten around to writing the local `.brackets.json` check for myself.
